apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nextcloud-kustom
  namespace: flux-system
spec:
  interval: 5m
  path: ./nextcloud/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: nextcloud
