apiVersion: helm.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    repository: https://nextcloud.github.io/helm/     # URL du référentiel Helm contenant le chart Nextcloud
    name: nextcloud                    # Nom du chart Nextcloud
    version: 26.0.2        # Version spécifique du chart Nextcloud à déployer
  values:
    redis:
      enabled: true 
      master:
       persistence: 
        enabled: false
       replica:
        persistence: 
         enabled: false
    externalDatabase: 
     enabled: false
    internalDatabase: 
     enabled: true 
     name: nextcloud
