#---
#apiVersion: apps/v1
#kind: Namespace
#metadata:
#  name: nextcloud
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 5m
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    repository: nextcloud
    name: nextcloud
    version: 26.0.2
  values:
    redis:
      enabled: true 
      master:
       persistence: 
        enabled: false
       replica:
        persistence: 
         enabled: false
  externalDatabase: 
   enabled: false
  internalDatabase: 
   enabled: true 
   name: nextcloud
