apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  url: https://nextcloud.github.io/helm/
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      version: "26.0.2"  # Remplacez par la version souhaitée de Nextcloud
  values:
    redis:
      enabled: true 
      master:
        persistence: 
          enabled: false
      replica:
        persistence: 
          enabled: false

    externalDatabase: 
      enabled: false
    internalDatabase: 
      enabled: true 
      name: nextcloud
  
